import { openDatabaseSync, SQLiteDatabase } from "expo-sqlite";
import { drizzle } from "drizzle-orm/expo-sqlite";
import * as schema from "./schema";

export const DB_NAME = "flagged.db";

let _sqlite: SQLiteDatabase | null = null;

/** Raw expo-sqlite handle (used for DDL and pragmas). */
export function sqlite(): SQLiteDatabase {
  if (!_sqlite) {
    _sqlite = openDatabaseSync(DB_NAME);
    _sqlite.execSync("PRAGMA journal_mode = WAL;");
    _sqlite.execSync("PRAGMA foreign_keys = ON;");
  }
  return _sqlite;
}

/** Drizzle client bound to the schema. */
export const db = drizzle(sqlite(), { schema });

/**
 * Create tables if they don't exist. In a production build these DDL statements
 * would be generated by drizzle-kit migrations; kept inline here so the
 * skeleton boots without a migration step.
 */
export function ensureTables(): void {
  const s = sqlite();
  s.execSync(`
    CREATE TABLE IF NOT EXISTS ingredients (
      id TEXT PRIMARY KEY NOT NULL,
      term TEXT NOT NULL
    );
    CREATE TABLE IF NOT EXISTS categories (
      id TEXT PRIMARY KEY NOT NULL,
      name TEXT NOT NULL,
      parent_group TEXT NOT NULL,
      classification TEXT NOT NULL
    );
    CREATE TABLE IF NOT EXISTS category_ingredient (
      category_id TEXT NOT NULL,
      ingredient_id TEXT NOT NULL,
      position INTEGER NOT NULL,
      PRIMARY KEY (category_id, ingredient_id)
    );
    CREATE TABLE IF NOT EXISTS quick_packs (
      id TEXT PRIMARY KEY NOT NULL,
      name TEXT NOT NULL,
      type TEXT NOT NULL
    );
    CREATE TABLE IF NOT EXISTS quick_pack_category (
      pack_id TEXT NOT NULL,
      category_id TEXT NOT NULL,
      position INTEGER NOT NULL,
      PRIMARY KEY (pack_id, category_id)
    );
    CREATE TABLE IF NOT EXISTS profiles (
      profile_id TEXT PRIMARY KEY NOT NULL,
      name TEXT NOT NULL,
      active_category_ids TEXT NOT NULL DEFAULT '[]',
      excluded_ingredient_ids TEXT NOT NULL DEFAULT '[]',
      custom_ingredients TEXT NOT NULL DEFAULT '[]',
      created_at INTEGER NOT NULL,
      total_labels_read INTEGER NOT NULL DEFAULT 0,
      total_red_flags_caught INTEGER NOT NULL DEFAULT 0,
      total_clean_scans INTEGER NOT NULL DEFAULT 0,
      total_skimpflation_caught INTEGER NOT NULL DEFAULT 0,
      total_reformulations_caught INTEGER NOT NULL DEFAULT 0
    );
    CREATE TABLE IF NOT EXISTS pantry_items (
      item_id TEXT PRIMARY KEY NOT NULL,
      profile_id TEXT NOT NULL DEFAULT '',
      brand_name TEXT NOT NULL,
      product_name TEXT NOT NULL,
      image_file_path TEXT NOT NULL DEFAULT '',
      original_ingredients TEXT NOT NULL DEFAULT '[]',
      date_added INTEGER NOT NULL,
      last_verified_date INTEGER NOT NULL,
      deleted_at INTEGER
    );
    CREATE TABLE IF NOT EXISTS stats (
      stats_id TEXT PRIMARY KEY NOT NULL,
      free_scans_used INTEGER NOT NULL DEFAULT 0,
      total_labels_read INTEGER NOT NULL DEFAULT 0,
      total_red_flags_caught INTEGER NOT NULL DEFAULT 0,
      total_clean_scans INTEGER NOT NULL DEFAULT 0,
      total_skimpflation_caught INTEGER NOT NULL DEFAULT 0,
      total_reformulations_caught INTEGER NOT NULL DEFAULT 0
    );
    CREATE TABLE IF NOT EXISTS app_meta (
      key TEXT PRIMARY KEY NOT NULL,
      value TEXT NOT NULL
    );
  `);
}

/**
 * Additive, non-destructive schema migrations for installs created before a
 * column existed. Each step is guarded by a PRAGMA check so it is idempotent.
 * In a production build these would be drizzle-kit migrations; kept inline so
 * the app boots without a migration runner.
 */
export function runMigrations(): void {
  const s = sqlite();
  const statsCols = s
    .getAllSync<{ name: string }>("PRAGMA table_info(stats)")
    .map((c) => c.name);

  if (!statsCols.includes("total_skimpflation_caught")) {
    s.execSync(
      "ALTER TABLE stats ADD COLUMN total_skimpflation_caught INTEGER NOT NULL DEFAULT 0"
    );
  }
  if (!statsCols.includes("total_reformulations_caught")) {
    s.execSync(
      "ALTER TABLE stats ADD COLUMN total_reformulations_caught INTEGER NOT NULL DEFAULT 0"
    );
  }

  // Per-profile dashboard counters (docs/17) — additive for installs created
  // before Home/Scan/Results were profile-aware.
  const profileCols = s
    .getAllSync<{ name: string }>("PRAGMA table_info(profiles)")
    .map((c) => c.name);
  for (const col of [
    "total_labels_read",
    "total_red_flags_caught",
    "total_clean_scans",
    "total_skimpflation_caught",
    "total_reformulations_caught",
  ]) {
    if (!profileCols.includes(col)) {
      s.execSync(`ALTER TABLE profiles ADD COLUMN ${col} INTEGER NOT NULL DEFAULT 0`);
    }
  }

  // Pantry items now belong to the profile that scanned them (docs/17 Pantry
  // mockup) — existing rows (pre-dating this) get '' and simply won't surface
  // under any specific profile, only under "All".
  const pantryCols = s
    .getAllSync<{ name: string }>("PRAGMA table_info(pantry_items)")
    .map((c) => c.name);
  if (!pantryCols.includes("profile_id")) {
    s.execSync("ALTER TABLE pantry_items ADD COLUMN profile_id TEXT NOT NULL DEFAULT ''");
  }
}
